name:                lab11
version:             0.1.0.0
license:             BSD3
author:              "Łukasz Klasiński"
copyright:           "2020 Łukasz Klasiński"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lab11#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src