Flags = -Wall -Wundef -std=c++17 -llua

zad1 : zad1.o 
	g++ -o out.o zad1.cpp $(Flags)\

zad2 : zad2.o
	g++ -o out.o zad2.cpp $(Flags)\

zad3 : zad3.o
	g++ -o out.o zad3.cpp $(Flags)\

clean :
	rm out.o zad*.o