#!/usr/bin/env python

import sys
import re

RULES = list( map( lambda x: (re.compile(x[0]), x[1]), [
    ( r'^@(.*)', r'\\includegraphics[width=\\linewidth]{\1}' ), # Images
    ( r'(.*)', r'\1  ' ), # Rest
] ) )

slides = sys.stdin.read().split( '\n\n' )

print( r"""
---
mainfont: Iosevka
header-includes: |
    \usepackage{adjustbox}
    \definecolor{foreground}{HTML}{262626}
    \definecolor{background}{HTML}{c0c0c0}
    \setbeamercolor{background canvas}{bg=background}
    \setbeamercolor{background}{parent=background canvas}
    \setbeamercolor{normal text}{fg=foreground}
    \setbeamertemplate{frametitle}{}
    \setbeamertemplate{footline}{}
---
""".lstrip() )

for (i, slide) in enumerate( slides ):
    lines = slide.splitlines()

    print( r'\vfill' )
    print( r'\begin{center}' )
    # print( r'\begin{adjustbox}{min width=\linewidth}' )

    for line in lines:
        for (rule, repl) in RULES:
            if rule.search( line ) != None:
                line = rule.sub( repl, line )
                break

        print( line )

    # print( r'\end{adjustbox}' )
    print( r'\end{center}' )

    if i != len( slides ) - 1:
        print( '\n# {.plain}\n' )
