#!/usr/bin/env bash

Xephyr :22 -screen 7016x4961 &
XEPHYR=$!

sleep 1

DISPLAY=:22 ../../sent presentation &
SENT=$!

num=`cat presentation | grep -E "^$" | wc -l`
let num=num+1

mkdir screens
cd screens

zenity --info --text "Press OK when presentation is fully loaded"

for i in `seq -w 00 $num`; do
    # notify-send "$i/$num"

    DISPLAY=:22 import -window root -quality 100 screen$i.jpg
    DISPLAY=:22 xdotool key space
    sleep 0.5
done

kill $SENT
kill $XEPHYR
